/**
 * Stable, machine-readable error codes returned to API clients.
 *
 * These are part of the public API contract (see
 * `architecture/14-api-design-standards.md`) and must remain stable.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  /** Access token verified but expired — clients should refresh. */
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  /**
   * Access token failed verification for any non-expiry reason. Fine-grained
   * cryptographic/claim failures deliberately collapse to this single code so
   * the API never acts as a token-verification oracle.
   */
  TOKEN_INVALID = 'TOKEN_INVALID',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  DEPENDENCY_FAILURE = 'DEPENDENCY_FAILURE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TRIP_NOT_BOOKABLE = 'TRIP_NOT_BOOKABLE',
  SEAT_ALREADY_RESERVED = 'SEAT_ALREADY_RESERVED',
  INVALID_SEAT_SELECTION = 'INVALID_SEAT_SELECTION',
  BOOKING_ALREADY_EXISTS = 'BOOKING_ALREADY_EXISTS',
  BOOKING_NOT_CANCELLABLE = 'BOOKING_NOT_CANCELLABLE',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  PRICE_CHANGED = 'PRICE_CHANGED',
  // Phase 12 — Payments.
  BOOKING_NOT_PAYABLE = 'BOOKING_NOT_PAYABLE',
  PAYMENT_ALREADY_SETTLED = 'PAYMENT_ALREADY_SETTLED',
  PAYMENT_NOT_CONFIRMABLE = 'PAYMENT_NOT_CONFIRMABLE',
  PAYMENT_NOT_REFUNDABLE = 'PAYMENT_NOT_REFUNDABLE',
  PAYMENT_METHOD_NOT_ALLOWED = 'PAYMENT_METHOD_NOT_ALLOWED',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
  // Phase 13 — Tickets.
  TICKET_NOT_ISSUABLE = 'TICKET_NOT_ISSUABLE',
  TICKET_ALREADY_ISSUED = 'TICKET_ALREADY_ISSUED',
  TICKET_NOT_VALIDATABLE = 'TICKET_NOT_VALIDATABLE',
}
