import { CORRELATION_ID_HEADER } from '../constants/request.constants';

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

interface CorrelationIdCarrier {
  correlationId?: unknown;
  headers: Record<string, string | string[] | undefined>;
}

interface HeaderWritableResponse {
  setHeader(name: string, value: string): void;
}

/** Whether a value is a canonical UUID suitable for correlation storage. */
export function isValidUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_PATTERN.test(value);
}

/** Return the request correlation id when it has passed UUID validation. */
export function getCorrelationId(request: {
  correlationId?: unknown;
}): string | undefined {
  return isValidUuid(request.correlationId) ? request.correlationId : undefined;
}

/**
 * Attach and echo a client-supplied correlation id only when it is a UUID.
 * Unlike request ids, correlation ids are never generated by the server.
 */
export function ensureCorrelationId(
  request: CorrelationIdCarrier,
  response: HeaderWritableResponse,
): string | undefined {
  const existing = getCorrelationId(request);
  const header = request.headers[CORRELATION_ID_HEADER];
  const incoming = Array.isArray(header) ? header[0] : header;
  const correlationId = existing ?? (isValidUuid(incoming) ? incoming : undefined);

  if (correlationId !== undefined) {
    request.correlationId = correlationId;
    response.setHeader(CORRELATION_ID_HEADER, correlationId);
  }

  return correlationId;
}
